server:
  port: 8347
spring:
  application:
    name: wheatmall-mini
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.237:3308/wheatmall_mini?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 不写该配置默认也是这个位置
  global-config:
    db-config:
      id-type: auto # id自增
      logic-delete-value: 1 # 逻辑删除打开
      logic-not-delete-value: 0
logging:
  level:
    com.ndz.wheatmall: debug # 开启项目包的debug模式即可打印sql执行详情

