server:
  port: 8347
spring:
  application:
    name: wheatmall-mini
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.237:3308/wheatmall_mini?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false # ture开启缓存，提高性能， false 关闭thymeleaf缓存，配合dev-tool可实时看到前端效果


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 不写该配置默认也是这个位置
  global-config:
    db-config:
      id-type: auto # id自增
      logic-delete-value: 1 # 逻辑删除打开
      logic-not-delete-value: 0
logging:
  level:
    com.ndz.wheatmall: debug # 开启项目包的debug模式即可打印sql执行详情

# knife4j 配置
#knife4j:
#  enable: true # 是否开启knife4j
#  openapi:
#    title: 麦子商城API
#    description: "麦子商城接口文档"
#    email: 535704264@qq.com
#    concat: Jack Lee
#    url: https://www.wheatmall.com
#    version: v1.0
#    license: Apache 2.0
#    license-url: http://www.apache.org/licenses/LICENSE-2.0
#    terms-of-service-url: https://www.wheatmall.com
#    group:
#      all:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.ndz.wheatmall